services:
  redis:
    image: redis:alpine
    container_name: clinic_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: clinic_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=True
      - ALLOWED_HOSTS=*
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: clinic_celery_worker
    command: celery -A clinic_appointment_system worker -l info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=True
      - ALLOWED_HOSTS=*
    depends_on:
      - redis
      - web